export const ADDTODO = 'todo/added'
export const REMOVETODO = 'todo/remove'
export const ALLCOMPLETED = 'todo/completed'
export const COLORSELECTED = 'todo/colorSelect'
export const TOGGLE = 'todo/toggle'
export const CLEARCOMPLETED = 'todo/clearCompleted'
export const STATUSCHANGED = 'todo/statusChanged'
export const COLORCHANGED = 'todo/colorChanged'